# https://github.com/Yamashou/gqlgenc?tab=readme-ov-file#client-codes-only

model:
  package: generated
  filename: ./generated/models.go
client:
  package: generated
  filename: ./generated/client.go
models:
  HTML:
    model: github.com/99designs/gqlgen/graphql.String
endpoint:
  url: http://localhost:8080/graphql
#   headers: # If you need header for getting introspection query, set it
#     Authorization: "Bearer ${API_TOKEN}" # support environment variables
query:
  - "./queries/*.gql" # Where are all the query files located?
generate:
  clientV2: true
  onlyUsedModels: true
