# https://github.com/Yamashou/gqlgenc?tab=readme-ov-file#client-codes-only

model:
  package: gql_gen
  filename: internal/clients/graphql/gen/models.go
client:
  package: gql_gen
  filename: internal/clients/graphql/gen/client.go
models:
  HTML:
    model: github.com/99designs/gqlgen/graphql.String
endpoint:
  url: http://localhost:8080/graphql
#   headers: # If you need header for getting introspection query, set it
#     Authorization: "Bearer ${API_TOKEN}" # support environment variables
query:
  - internal/clients/graphql/queries/*.gql
generate:
  clientV2: true
  onlyUsedModels: true
  clientInterfaceName: "GenGraphQLClient"
