openapi: 3.0.0
info:
  title: Mock API server
  version: 1.0.0
paths:
  /products:
    post:
      summary: Create N-products
      operationId: CreateProducts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductsRequest"
      responses:
        200:
          description: "OK: created N-products"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateProductsResponse"
        400:
          description: Bad Request - Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInputResponse"
components:
  schemas:
    ErrorInputResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Invalid input"
    CreateProductsRequest:
      type: object
      required:
        - quantity
      properties:
        quantity:
          type: integer
          format: int
          example: 3
    CreateProductsResponse:
      type: object
      required:
        - quantity
      properties:
        quantity:
          type: integer
          format: int
          example: 3
