openapi: 3.0.0
info:
  title: Mock API server
  version: 1.0.0
tags:
  - name: product
    description: Everything related to Products
paths:
  /products:
    post:
      tags:
        - product
      summary: Create N-products
      operationId: CreateProducts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductsRequest"
      responses:
        200:
          description: "OK: created N-products"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateProductsResponse"
        400:
          description: Bad Request - Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInputResponse"
    delete:
      tags:
        - product
      summary: Delete N-products
      operationId: DeleteProducts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteProductsRequest"
      responses:
        200:
          description: "OK: deleted N-products"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteProductsResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteProductsResponseError"
        422:
          description: Bad Request - Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInputResponse"

components:
  schemas:
    ErrorInputResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Invalid input"
    CreateProductsRequest:
      type: object
      required:
        - quantity
      properties:
        quantity:
          type: integer
          format: int
          example: 3
          description: number of mock entities
    CreateProductsResponse:
      type: object
      required:
        - quantity
      properties:
        quantity:
          type: integer
          format: int
          example: 3
    DeleteProductsRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: array
          items:
            type: string
          example: ["811", "812", "813"]
          description: IDs of products that should be removed
    DeleteProductsResponse:
      type: object
      required:
        - quantity
        - id
      properties:
        quantity:
          type: integer
          format: int
          example: 10
        id:
          type: array
          items:
            type: string
          example: ["811", "812", "813"]
          description: IDs of products that were successfully removed
    DeleteProductsResponseError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
