openapi: 3.0.0
info:
  title: Mock API server
  version: 1.0.0
servers:
  - url: http://localhost:8888
tags:
  - name: product
    description: Everything related to Products
paths:
  /products:
    post:
      tags:
        - product
      summary: Create N-products
      operationId: CreateProducts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductsRequest"
      responses:
        200:
          description: N-products or some part of them have been successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateProductsResponse"
              examples:
                fullSuccess:
                  summary: All products created successfully
                  value:
                    quantity: 3
                    productsId: ["234", "235", "236"]
                    errors: []
                partialSuccess:
                  summary: Partial success (3 out of 5)
                  value:
                    quantity: 3
                    productsId: ["234", "235", "236"]
                    errors:
                      - message: "error details"
                      - message: "error details"
        400:
          description: Request failed completely or partially
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateProductsResponseError"
        422:
          description: Bad Request - Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInputResponse"
    delete:
      tags:
        - product
      summary: Delete N-products
      operationId: DeleteProducts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteProductsRequest"
      responses:
        200:
          description: Successfully deleted N-products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteProductsResponse"
        400:
          description: Request failed completely or partially
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteProductsResponseError"
        422:
          description: Bad Request - Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInputResponse"

components:
  schemas:
    ErrorInputResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Invalid input"
    # products — create
    CreateProductsRequest:
      type: object
      required:
        - quantity
      properties:
        quantity:
          type: integer
          format: int
          example: 3
          description: number of mock entities
    CreateProductsResponse:
      type: object
      required:
        - quantity
        - productsId
        - errors
      properties:
        quantity:
          type: integer
          format: int
          example: 3
        productsId:
          type: array
          items:
            type: string
          example: ["811", "812", "813"]
          description: IDs of products that were successfully created
        errors:
          type: array
          description: Array of errors for failed product creations
          items:
            $ref: "#/components/schemas/CreateProductErrorItem"
    CreateProductsResponseError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: failed to create any products

    CreateProductErrorItem:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message describing why the product creation failed
          example: "failed to upload image: connection timeout"

    # products — delete
    DeleteProductsRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: array
          items:
            type: string
          example: ["811", "812", "813"]
          description: IDs of products that should be removed
    DeleteProductsResponse:
      type: object
      required:
        - quantity
        - id
      properties:
        quantity:
          type: integer
          format: int
          example: 3
        id:
          type: array
          items:
            type: string
          example: ["811", "812", "813"]
          description: IDs of products that were successfully removed
    DeleteProductsResponseError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: some products failed to delete
